Se agrega ultimos cambios a la receta y script de ayuda

diff --git a/bin/change_state b/bin/change_state
--- a/bin/change_state
+++ b/bin/change_state
@@ -1,6 +1,31 @@
 #!/usr/bin/env bash
 
-SERVER_ID=${1?-You must specify the server id}
-STATE=${2:-follower}
+function get_server_ip() {
+  if [ "${SOURCE}" == "local" ]; then
+    echo "localhost:5005${SERVER_INDEX}"
+  elif [ "${SOURCE}" == "aws" ]; then
+    local tf_output
+    local index
+    local server_ip
+    tf_output=$(cd infra/terraform && terraform output -json)
+    index="$((SERVER_INDEX - 1))"
+    server_ip=$(echo "$tf_output" | jq -r --argjson index "$index" '.public_ips.value[$index]')
+    echo "${server_ip}:50051"
+  fi
+}
 
-grpcurl -plaintext -proto private/grpc/server.proto -d "{\"membership_state\": \"${STATE}\"}" "localhost:5005${SERVER_ID}" raft.server.GRPC.SetMembership
+SERVER_INDEX=${1?-You must specify the server index}
+STATE=${2:-follower}
+SOURCE=${3:-local}
+
+if [ "$SOURCE" != "aws" ] && [ "$SOURCE" != "local" ]; then
+  echo "Invalid option"
+  echo "Choose one of"
+  echo -e "\t * 'local': local deployment with docker-compose. Default option"
+  echo -e "\t * 'aws': deployment with terraform+ansible"
+  exit 1
+fi
+
+SERVER_IP=$(get_server_ip)
+
+grpcurl -plaintext -proto private/grpc/server.proto -d "{\"membership_state\": \"${STATE}\"}" "${SERVER_IP}" raft.server.GRPC.SetMembership
diff --git a/bin/show_state b/bin/show_state
--- a/bin/show_state
+++ b/bin/show_state
@@ -1,10 +1,38 @@
 #!/usr/bin/env bash
 
+SOURCE=${1:-local}
+
+if [ "$SOURCE" != "aws" ] && [ "$SOURCE" != "local" ]; then
+  echo "Invalid option"
+  echo "Choose one of"
+  echo -e "\t * 'local': local deployment with docker-compose. Default option"
+  echo -e "\t * 'aws': deployment with terraform+ansible"
+  exit 1
+fi
+
+function get_state_local() {
+  local server_host
+  for i in {1..5}; do
+    server_host="localhost:5005${i}"
+    echo "Server: ${server_host}"
+    grpcurl -plaintext -proto private/grpc/server.proto "${server_host}" raft.server.GRPC.GetStatus
+  done;
+}
+
+function get_state_aws() {
+  local tf_output
+  local server_host
+  tf_output=$(cd infra/terraform && terraform output -json)
+  for ip in $(echo "$tf_output" | jq -rc ".public_ips.value[]"); do
+    server_host="${ip}:50051"
+    echo "Server: ${server_host}"
+    grpcurl -plaintext -proto private/grpc/server.proto "${ip}:50051" raft.server.GRPC.GetStatus
+  done
+}
+
 while true; do
     echo "State";
-    for i in {1..5}; do
-        grpcurl -plaintext -proto private/grpc/server.proto localhost:5005$i raft.server.GRPC.GetStatus
-    done;
+    "get_state_${SOURCE}"
     echo "==============================="
     sleep 1
 done
